language: elixir
elixir:
  - 1.5
  - 1.6
  - 1.7
otp_release:
  - 19.0
  - 20.3
matrix:
  include:
    - elixir: 1.8
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 21.0
script: mix test
env:
  - MIX_ENV=test
before_install:
  - sudo apt-get install graphviz
